### ISSUE TITLE
nix shell in README should be replaced with nix develop

### ISSUE THREAD

**Issue by ostrolucky** [loophp/nix-shell#122]
`nix shell` as README specifies did not work for me (seemingly nothing happened after executing it), but then I noticed that in GIF you use `nix develop`. That correctly changes my terminal to new environment.

**Comment by drupol** [comment]
Hi!

I will update the readme tomorrow, thanks for letting me know about this little quirk.

**Comment by drupol** [comment]
Dear @ostrolucky ,

I tested `nix shell github:loophp/nix-shell#php82` and it works does the job.

Can you try again and tell me ?

Thanks!

**Comment by ostrolucky** [comment]
This is how it behaves for me https://asciinema.org/a/NPNWzv96R2MYu2paaz0nEPRYY

**Comment by drupol** [comment]
I see.

I think everything is working fine.

- When you do `nix shell github:loophp/nix-shell#php82`, you enter a shell where all the PHP tools are available (php, composer, gnu make, symfony, etc etc)
- When you do `nix develop github:loophp/nix-shell#php82` you enter in the same shell, but it's using by default `bash`.

One way to verify if it works, you could do just: `php -v` and see if your version of PHP is PHP 8.2.1.

Let me know the outcome.

**Comment by ostrolucky** [comment]
```
➜  Documents nix shell github:loophp/nix-shell#php82
➜  Documents php -v
PHP 8.0.27 (cli) (built: Jan 12 2023 04:00:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
    with Zend OPcache v8.0.27, Copyright (c), by Zend Technologies
➜  Documents which php
/opt/homebrew/opt/php@8.0/bin/php
➜  Documents
```

**Comment by drupol** [comment]
Ho nose.

I wish I could have a Mac to test this out.

Maybe @stephank may help here ?

**Comment by ostrolucky** [comment]
We found PHP specified via homebrew was taking over because it was in a $PATH first. Issue solved :)
