### ISSUE TITLE
Importing extensions from composer.json/lock does not work anymore while building a devShell

### ISSUE THREAD

**Issue by buurro** [loophp/nix-shell#139]
## Steps required to reproduce the problem

1. Add some extensions to `composer.json`:
```json
"require-dev": {
    "ext-xdebug": "*"
}
```
2. Run `composer install` to generate the lock file
3. Use `nix-shell.api.makePhp` in `flake.nix` to generate a devShell as per example in README
4. Run `nix develop --impure`

## Expected Result

* `php --info | grep xdebug` returning xdebug configuration

## Actual Result

* `php --info | grep xdebug` returns nothing

**Comment by drupol** [comment]
This should be fixed now, can you try and let me know?

**Comment by buurro** [comment]
Everything works now! Thank you so much.

**Comment by drupol** [comment]
Cool, glad to see that this is useful :)
