### ISSUE TITLE
Error while launching nix shell : The foobar extension does not exist, ignoring.

### ISSUE THREAD

**Issue by rivallinkil** [loophp/nix-shell#174]
## Steps required to reproduce the problem

1. A composer.json with some extensions required : rdkafka, sodium, pcov, etc.
2. A .user.ini to change memory_limit
3. Launch a nix shell with the following command : 
`github:loophp/nix-shell#env-php82 --impure
`
## Expected Result

- Nix Shell with extension load and memory limit changed.

## Actual Result

- Error message "warning: The foobar extension does not exist, ignoring."

I read the new flake.nix and I saw your new modification : .user.ini is no longer used in configuration and the composer.json read is that local to the repository. 
What can I do to get back to the old behaviour ? Thanks for your help 😄

**Comment by drupol** [comment]
Looks like I merge something too quickly. I've reverted the commit introducing the issue, should be good now :)

Sorry for the mess!

**Comment by drupol** [comment]
Feel free to close the issue if it's fixed on your side.

**Comment by drupol** [comment]
I pushed a new commit just now where the issue you reported has been fixed in https://github.com/loophp/nix-php-composer-builder/commit/8d4382bd4149502fbf4605cb6f43c1017cb6156a
