### ISSUE TITLE
Xdebug PHP extension no more infered from composer.json

### ISSUE THREAD

**Issue by leNEKO** [loophp/nix-shell#200]
## Steps required to reproduce the problem

With a `composer.json` where `ext-xdebug` is required
```json
{
...
   "require": {
        "php": "~8.2"
    },
    "require-dev": {
        "ext-xdebug": "*",
    }
...
}
```

1. run `nix shell github:loophp/nix-shell#env-php82 --impure`
2. run `php --version`

## Expected Result

```shell
PHP 8.2.11 (cli) (built: Sep 26 2023 11:11:58) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
```

(it works with a previous commit `nix shell github:loophp/nix-shell/939d9#env-php82 --impure`)

## Actual Result

```shell
PHP 8.2.11 (cli) (built: Sep 26 2023 11:11:58) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies
```

**Comment by leNEKO** [comment]
A previous commit where it works: https://github.com/loophp/nix-shell/commit/939d9cefc2c93fcddc644e7f20d2f45787c5f5d9

**Comment by drupol** [comment]
Thanks, going to check what's going on tomorrow...

**Comment by leNEKO** [comment]
@drupol it works again :) Thank you !
