### ISSUE TITLE
Nix experimental features

### ISSUE THREAD

**Issue by norberttech** [loophp/nix-shell#47]
## Steps required to reproduce the problem

1. run `nix shell github:loophp/nix-shell#php74` at MacOS without experimental features enabled

## Expected Result

* `building php-7.4...` 

## Actual Result

* `error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override` 

On macOS running commands from README would throw an error, it can be fixed by enabling experimental features. 

```
# ~/.config/nix/nix.conf
experimental-features = nix-command flakes
```

Maybe it would be good to mention this behavior somewhere in the readme?

**Comment by drupol** [comment]
Hi @norberttech !

Indeed, we could add it.

The README needs a cleanup and some more documentation, I'll try to focus on that during July.

**Comment by drupol** [comment]
@norberttech I just pushed a fix.
